### ISSUE TITLE
Sass Rails Asset Pipeline Failure

### ISSUE THREAD

**Issue by nickbabcock** [mitre/cedar#4]
For `exec rake assets:precompile`, the following error occurs:

```
rake aborted!
Sass::SyntaxError: Undefined variable: "$alert-padding".
  (in /usr/local/bundle/gems/bootstrap-sass-3.3.5/assets/stylesheets/bootstrap/_alerts.scss:10)
/usr/local/bundle/gems/bootstrap-sass-3.3.5/assets/stylesheets/bootstrap/_alerts.scss:10
/usr/local/bundle/gems/sass-3.2.19/lib/sass/script/variable.rb:49:in `_perform'
```

I'm not sure if this is the problem, but based on [bootstrap-sass' README](https://github.com/twbs/bootstrap-sass#a-ruby-on-rails):
- There really shouldn't be any `.css` stylesheets under `app` (they should be `.scss`).
- Instead of using `*= require`, use sass `@imports`.
- Doesn't bootstrap-sass include bootstrap such that `bootstrap.css` doesn't need to be included as a vendored file?

**Comment by notpace** [comment]
I've been meaning to clean up a bunch of the rails pipeline assets, but I don't think that's the root cause.  There's a good discussion by some other users with similar issues over here: https://github.com/twbs/bootstrap-sass/issues/653

**Comment by notpace** [comment]
After a bit more digging, I think this has to do with the order in which assets are being called for precompile.  There's a good writeup (http://stackoverflow.com/questions/9915950/bootstrap-sass-undefined-variable-baselineheight) about the build order that suggests removing all `.css` and `.js` files from the precompile since they should be incorporated via `application.scss` and `application.js`.  Commit 531f2a0 should address this.

**Comment by nickbabcock** [comment]
Shoot, turns out I was close :stuck_out_tongue: 

No more asset pipeline issues, thanks guys!
